# Generated by Django 4.0.3 on 2022-04-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('tipos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valor', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('grupos', models.ManyToManyField(to='inventario.grupos')),
                ('marcos', models.ManyToManyField(to='inventario.marcos')),
                ('tipo_de_cicla', models.ManyToManyField(to='tipos.tipos_de_bicicletas')),
                ('zapatillas', models.ManyToManyField(to='inventario.zapatillas')),
            ],
        ),
    ]
