# Generated by Django 3.2 on 2022-04-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='grupos',
        ),
        migrations.AddField(
            model_name='ventas',
            name='grupos',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.grupos'),
            preserve_default=False,
        ),
    ]
