# Generated by Django 4.0.3 on 2022-04-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo_de_cicla', models.CharField(max_length=50)),
                ('hora_de_inicio', models.DateTimeField()),
                ('hora_de_fin', models.DateTimeField()),
                ('valor', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
