# Generated by Django 4.0.3 on 2022-04-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos', '0001_initial'),
        ('alquiler', '0002_alter_alquiler_tipo_de_cicla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='tipo_de_cicla',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='tipo_de_cicla',
            field=models.ManyToManyField(to='tipos.tipos_de_bicicletas'),
        ),
    ]
