# Generated by Django 4.0.3 on 2022-04-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_remove_alquiler_tipo_de_cicla_alquiler_tipo_de_cicla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='tipo_de_cicla',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='tipo_de_cicla',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
