# Generated by Django 4.0.3 on 2022-04-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos', '0001_initial'),
        ('alquiler', '0004_remove_alquiler_tipo_de_cicla_alquiler_tipo_de_cicla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='tipo_de_cicla',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='tipo_de_cicla',
            field=models.ManyToManyField(to='tipos.tipos_de_bicicletas'),
        ),
    ]
