# Generated by Django 3.2 on 2022-04-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0005_remove_alquiler_tipo_de_cicla_alquiler_tipo_de_cicla'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='devuelto',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
