# Generated by Django 3.2 on 2022-04-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_de_bicicletas',
            name='descripcion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipos_de_bicicletas',
            name='garantia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
