# Generated by Django 4.0.3 on 2022-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('velocidades', models.CharField(max_length=40)),
                ('garantia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marcos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=50)),
                ('garantia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zapatillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('talla', models.CharField(max_length=2)),
                ('estilo', models.CharField(max_length=40)),
            ],
        ),
    ]
