# Generated by Django 3.2 on 2022-04-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipos', '0001_initial'),
        ('reparacion', '0002_remove_reparacion_tipo_de_cicla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='tipo_de_cicla',
        ),
        migrations.AddField(
            model_name='reparacion',
            name='tipo_de_cicla',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipos.tipos_de_bicicletas'),
            preserve_default=False,
        ),
    ]
