# Generated by Django 3.2 on 2022-04-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('reparacion', '0004_auto_20220418_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='cliente',
        ),
        migrations.AddField(
            model_name='reparacion',
            name='cliente',
            field=models.ManyToManyField(to='clientes.Clientes'),
        ),
    ]
