# Generated by Django 4.0.3 on 2022-04-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecanico', '0002_reparacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reparacion',
        ),
    ]
